//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosORM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class CatDireccion
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public CatDireccion()
        //{
        //    this.CatAgentes = new HashSet<CatAgentes>();
        //}
    
        [Key]
        public int IdDireccion { get; set; }
        public string Calle { get; set; }
        public Nullable<int> NumInterior { get; set; }
        public Nullable<int> NumExterior { get; set; }
        public string Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdPais { get; set; }
        public Nullable<int> Estatus { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CatAgentes> CatAgentes { get; set; }
        //public virtual CatMunicipio CatMunicipio { get; set; }
        //public virtual CatEstado CatEstado { get; set; }
        //public virtual CatPais CatPais { get; set; }
    }
}
