//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosORM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class CatEstado
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public CatEstado()
        //{
        //    this.CatMunicipio = new HashSet<CatMunicipio>();
        //    this.CatDireccion = new HashSet<CatDireccion>();
        //}
    
        [Key]
        public int IdEstado { get; set; }
        public string NombreEstado { get; set; }
        public string Ciudad { get; set; }
        public int IdPais { get; set; }
        public int Estatus { get; set; }
    
        //public virtual CatPais CatPais { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CatMunicipio> CatMunicipio { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CatDireccion> CatDireccion { get; set; }
    }
}
