//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosORM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FormaDePago
    {
        [Key]
        public int IdFormaPago { get; set; }
        public string FormaPago { get; set; }
        public Nullable<int> InformacionExtra { get; set; }
        public Nullable<int> Estatus { get; set; }
    }
}
