//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosORM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Menu
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public Menu()
        //{
        //    this.MenuxUsr = new HashSet<MenuxUsr>();
        //}
    
        [Key]
        public string NombreMenu { get; set; }
        public int IdentificadorMenu { get; set; }
        public Nullable<int> IdentificadorPadre { get; set; }
        public string NombreFormulario { get; set; }
        public Nullable<int> Estatus { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<MenuxUsr> MenuxUsr { get; set; }
    }
}
