//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosORM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class MenuxUsr
    {
        [Key]
        public int IdUsuario { get; set; }
        public Nullable<int> NivelUsuario { get; set; }
        public int IdentificadorMenu { get; set; }
        public Nullable<int> Estatus { get; set; }
    
        //public virtual Menu Menu { get; set; }
        //public virtual Usuario Usuario { get; set; }
    }
}
