//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Navitur1Entities : DbContext
    {
        public Navitur1Entities()
            : base("name=Navitur1Entities")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        public virtual DbSet<CatAgentes> CatAgentes { get; set; }
        public virtual DbSet<CatDireccion> CatDireccion { get; set; }
        public virtual DbSet<CatEstado> CatEstado { get; set; }
        public virtual DbSet<CatMunicipio> CatMunicipio { get; set; }
        public virtual DbSet<CatPais> CatPais { get; set; }
        public virtual DbSet<FormaDePago> FormaDePago { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<MenuxUsr> MenuxUsr { get; set; }
        public virtual DbSet<Privilegio> Privilegio { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<BitacoraEventos> BitacoraEventos { get; set; }
    }
}
